### PR TITLE
#1161: case for "null | string" enum with flag.

### LINKED ISSUE #1161: Property type "null | string" does not add StringEnumConverter attribute.
NJsonSchema.CodeGeneration.CSharp (10.1.12)

When there is a 
```json
    "myProperty": {
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "AS_PER_GTC",
        "AS_PER_TTB",
        "AS_PER_CP",
        "NONE",
        null
      ]    },
```

The StringEnumConverter attribute is not being added.
```csharp
[Newtonsoft.Json.JsonProperty("myProperty", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public MyClassMyProperty? MyProperty
{
	get;
	set;
}
```

```csharp
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.12.0 (Newtonsoft.Json v9.0.0.0)")]
[System.Flags]
public enum LogisticsNominationClause
{
	[System.Runtime.Serialization.EnumMember(Value = @"AS_PER_GTC")]
	AS_PER_GTC = 1,
	[System.Runtime.Serialization.EnumMember(Value = @"AS_PER_TTB")]
	AS_PER_TTB = 2,
	[System.Runtime.Serialization.EnumMember(Value = @"AS_PER_CP")]
	AS_PER_CP = 4,
	[System.Runtime.Serialization.EnumMember(Value = @"NONE")]
	NONE = 8,
}
```

Probably because:
*PropertyModel.cs*
```csharp
/// <summary>Gets a value indicating whether the property type is string enum.</summary>
public bool IsStringEnum
{
  get
  {
	if (this._property.ActualTypeSchema.IsEnumeration)
	  return this._property.ActualTypeSchema.Type == JsonObjectType.String;
	return false;
  }
}
```

### PR DESCRIPTION
**Pull request by ikutsin**
fixes #1161

### CODE REVIEW

**Comment by RicoSuter** [comment]
Maybe its better to use HasFlag(String) instead of the ||

**Comment by ikutsin** [comment]
Done. Thank you. 
When do you think it will be pushed to nuget feed?

**Comment by RicoSuter** [comment]
You just need the njs lib?

**Comment by ikutsin** [comment]
> You just need the njs lib?

I'd like to have nuget to put the change into our master branch. But It is fine just to know ETA, no rush for release.

**Pull request merged**
