### PR TITLE
Bugfix/external $ref resolving

### PR DESCRIPTION
**Pull request by davidmbillie**
My team has an API conformance testing project that utilizes the NJsonSchema library to read yaml specs and validate response data against expected schemas parsed from the specs. The functionality worked when our API Governance team's specs all had $refs contained in single file; however, they are going in the direction of having $refs to schemas in external files for things such as headers and responses.

We started experiencing the "System.InvalidOperationException: Could not resolve the JSON path..." errors similar to the one mentioned in [issue 566](https://github.com/RicoSuter/NJsonSchema/issues/566) when trying to load an external $ref from a `headers.yaml` file from a base `specification.yaml` file. First, I checked if the `headers.yaml` file was formatted correctly by loading it through the `FromFileAsync` method individually, and it worked. So I debugged through NJsonSchema with the base `specification.yaml`, and found that the external schema was being loaded in as an <string, object> Dictionary instead of a JsonSchema, causing an internal InvalidCastException. Adding a condition to `ResolveDocumentReferenceWithoutDereferencing` in `JsonReferenceResolver.cs` to check if the obj is an IDictionary then converting it to a JsonSchema with `FromJsonWithCurrentSettings` worked to resolve the $refs.

However, after solving that ref issue, another occurred when trying to resolve $refs for schemas in an external `responses.yaml` file. I found a similar problem in [issue 1171](https://github.com/RicoSuter/NSwag/issues/1171), but we received a "Unable to cast object of type 'NJsonSchema.JsonSchema' to type 'NSwag.OpenApiResponse'." The exception was happening in `IJsonReferenceBase.Reference`, where in this case `value` was type JsonSchema and `T`  was type OpenApiResponse. I solved this issue by checking if `value` was type T, and if not, getting the Reference property from `value` and casting that to type T. With these changes, our integration tests pass.

### CODE REVIEW

**Comment by RicoSuter** [comment]
Can you add a unit test which reproduces the initial problem?

**Comment by davidmbillie** [comment]
I included a generic version of the problem spec with its external ref files. I also noticed that the response still wasn't loaded correctly in my test, so I edited my condition for setting the reference property in JsonReferenceBase.

**Comment by davidmbillie** [comment]
@RicoSuter Can I request a review for this? I have an internal issue open for it.

**Comment by RicoSuter** [comment]
i’m extremely hesitant to change something on this base functionality (ref handling) - mainly because i’m the guy who has to fix it if it blows up for someone (which happened often). I hope i get the time to look into this soon.

**Comment by davidmbillie** [comment]
Thank you, and I understand. I'd be willing to write more tests for any scenarios that come to find for you as well.

**Comment by davidmbillie** [comment]
@RicoSuter  I'll also add that the conditions I wrote should only affect fringe cases that would have always been failing. Like an IDictionary would have always thrown an exception when doing a hard cast to an IJsonReference. The base functionality of $ref handling should not be touched by these changes.

**Comment by davidmbillie** [comment]
@RicoSuter Sorry to bug, but has this been looked into at all?

**Comment by luk355** [comment]
@RicoSuter, just to add to this, the current version in master does have quite a few issues in ref handling and would really appreciate if this PR can be looked at. Just to name a few:
 * references in `/components/parameters` does not work at all
 * path reference to external file does not work
    ```yaml
       paths:
          "foo":
              $ref: "foo.yaml#/paths/~1foo"
    ```
  * basically any external reference outside of `/components/schemas` is not being resolved

These issues make the tool unusable for any more complicated schemas when the schema is separated into multiple files.

I understand the amount of work you've put into this so far. It would be shame to leave these issues in. Thank you!

and lastly, thanks @davidmbillie for implementing the fix.

**Comment by RicoSuter** [comment]
For path you’d need this, right?
https://github.com/RicoSuter/NSwag/pull/1953

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NJsonSchema/issues/588

**Comment by davidmbillie** [comment]
> For path you’d need this, right?
> [RicoSuter/NSwag#1953](https://github.com/RicoSuter/NSwag/pull/1953)

It looks like so, but I haven't come across any concrete cases with path refs like that yet. If you'd like, I can merge your PR branch into mine and try to write a test for it.

**Comment by RicoSuter** [comment]
This one is in NJS and the other in NSwag so you cannot really merge it, right? :)

**Comment by RicoSuter** [comment]
Ill have some time to look into this tomorrow...

**Comment by davidmbillie** [comment]
> This one is in NJS and the other in NSwag so you cannot really merge it, right? :)

Haha yeah, my bad. I'll still look into writing the unit test for that NJS PR too.

**Comment by RicoSuter** [comment]
Ok, I've updated the code to avoid cloning objects in the setter and also to use the correct serializer... 
Tests still pass and i fixed another issue as well... can you check my changes? Is this ok?

**Pull request merged**
