### PR TITLE
Add System.Text.Json ExtensionData attribute tests

### PR DESCRIPTION
**Pull request by deceptiveSimplicity**
As requested in https://github.com/RicoSuter/NSwag/issues/3280

### CODE REVIEW

**Comment by RicoSuter** [comment]
Updated and fixed test. Please review.

**Comment by RicoSuter** [comment]
Decided to merge :-)
Ping me if there is a problem with the PR.

**Comment by deceptiveSimplicity** [comment]
Sorry for being late...
The change looks good to me. :)
I haven't tested it with NSwag and the model in https://github.com/RicoSuter/NSwag/issues/3280, but I think this change should fix the problem. I'll give more feedback in the issue when I tested it.

**Comment by RicoSuter** [comment]
NSwag is not yet updated with this change... will update and release probably today

**Comment by deceptiveSimplicity** [comment]
I know, that's why I haven't tested it yet. It is a bit more complicated to test NSwag and NJsonSchema from source in my solution. I will wait for your release. Thank you very much for your work.

**Pull request merged**
