### PR TITLE
Prepare for NET 9 SDK analysis

### PR DESCRIPTION
**Pull request by lahma**
NET 9 SDK has more rules and will cause build problems. Creating a TODO list for focused PRs in `Directory.Build.props` via `NoWarn` items, fixing small easy wins inside the PR. Now compiles with NET 9 SDK. All changes made with IDE automation.

### CODE REVIEW

**Comment by RicoSuter** [comment]
@lahma can you maybe also add a fix for this windows CI build failure (conflict)?

image

**Comment by lahma** [comment]
Sure, gimme an hour so that I get back to computer, I've dealt with this before.

**Comment by RicoSuter** [comment]
Thanks for the fix, can we merge this PR then?
Is this necessary for new NSwag release or can this also wait?

**Comment by lahma** [comment]
Can be merged. This is not needed for NSwag, but if you want to compile with NET 9 SDK (global.json now only allows 8.0) there would be compile errors, after this, no more. I can create a separate PR to switch to NET 9 SDK or add is as part of this too.

**Comment by RicoSuter** [comment]
> Can be merged. This is not needed for NSwag, but if you want to compile with NET 9 SDK (global.json now only allows 8.0) there would be compile errors, after this, no more. I can create a separate PR to switch to NET 9 SDK or add is as part of this too.

Yes please update PR to use .NET 9 then...
So the changes are "cosmetic" only right?

**Comment by lahma** [comment]
@RicoSuter now uses (and requires) NET 9 SDK when building.

**Pull request merged**
