### PR TITLE
JsonSchemaValidator validate nullable type

### PR DESCRIPTION
**Pull request by gcelet**
Allow validation of different SchemaType by JsonSchemaValidator #865 

ie also validate openapi and swagger

### CODE REVIEW

**Comment by gcelet** [comment]
That's what i thought first but ValidateXXX methods add error when they see JTokenType.Null 😞

**Comment by gcelet** [comment]
Sorry about the delay: it was a busy week at work. 
i hope i can work on it on monday. 
I'm currently using this version (via a big copy & paste) which works well in my case (although only in open api mode).

**Comment by RSuter** [comment]
No problem and no hurry... have a nice weekend.

**Comment by RicoSuter** [comment]
Any update on this PR?

**Comment by gcelet** [comment]
Hi,

Sorry about the stale PR: i've been very busy at work.

Honestly, i don't think i'll have time before summer to work on this. Maybe you can close it for the time being ?

For the record, i'm still using successfully  a copy paste custom JsonSchemaValidator like this one:

```csharp
public class JsonSchemaValidatorCustom
    {
        #region --- Static Fields ---

        private static readonly IEnumerable<JsonObjectType> JsonObjectTypes = Enum
            .GetValues(typeof(JsonObjectType))
            .Cast<JsonObjectType>()
            .Where(t => t != JsonObjectType.None)
            .ToList();

        #endregion

        #region --- Fields ---

        private readonly IEnumerable<IFormatValidator> _formatValidators = new IFormatValidator[]
        {
            new DateTimeFormatValidator(),
            new DateFormatValidator(),
            new EmailFormatValidator(),
            new GuidFormatValidator(),
            new HostnameFormatValidator(),
            new IpV4FormatValidator(),
            new IpV6FormatValidator(),
            new TimeFormatValidator(),
            new TimeSpanFormatValidator(),
            new UriFormatValidator(),
            new ByteFormatValidator(),
            new Base64FormatValidator()
        };

        private readonly IDictionary<string, IFormatValidator> _formatValidatorsMap;

        private readonly SchemaType _schemaType;

        #endregion

        #region --- Constructors ---

        /// <summary>
        /// Initializes JsonSchemaValidator
        /// </summary>
        public JsonSchemaValidatorCustom(SchemaType schemaType)
        {
            _schemaType = schemaType;
            _formatValidatorsMap = _formatValidators.ToDictionary(v => v.Format, v => v);
        }

        #endregion

        #region --- Public Methods ---

        /// <summary>Validates the given JSON data.</summary>
        /// <param name="jsonData">The json data.</param>
        /// <param name="schema">The schema.</param>
        /// <exception cref="JsonReaderException">Could not deserialize the JSON data.</exception>
        /// <returns>The list of validation errors.</returns>
        public ICollection<ValidationError> Validate(string jsonData, JsonSchema4 schema)
        {
            JToken jsonObject = JToken.Parse(jsonData);
            return Validate(jsonObject, schema);
        }

        /// <summary>Validates the given JSON token.</summary>
        /// <param name="token">The token.</param>
        /// <param name="schema">The schema.</param>
        /// <returns>The list of validation errors.</returns>
        public ICollection<ValidationError> Validate(JToken token, JsonSchema4 schema)
        {
            return Validate(token, schema.ActualSchema, null, token.Path);
        }

        #endregion

        #region --- Non Public Methods ---

        private string GetPropertyPath(string propertyPath, string propertyName)
        {
            return !string.IsNullOrEmpty(propertyPath) ? propertyPath + "." + propertyName : propertyName;
        }

        private IEnumerable<JsonObjectType> GetTypes(JsonSchema4 schema)
        {
            return JsonObjectTypes.Where(t => schema.Type.HasFlag(t));
        }

        private ChildSchemaValidationError TryCreateChildSchemaError(JToken token, JsonSchema4 schema,
            ValidationErrorKind errorKind, string property, string path)
        {
            ICollection<ValidationError> errors = Validate(token, schema.ActualSchema, null, path);
            if (errors.Count == 0)
            {
                return null;
            }

            Dictionary<JsonSchema4, ICollection<ValidationError>> errorDictionary =
                new Dictionary<JsonSchema4, ICollection<ValidationError>>();
            errorDictionary.Add(schema, errors);

            return new ChildSchemaValidationError(errorKind, property, path, errorDictionary, token, schema);
        }

        /// <summary>Validates the given JSON token.</summary>
        /// <param name="token">The token.</param>
        /// <param name="schema">The schema.</param>
        /// <param name="propertyName">The current property name.</param>
        /// <param name="propertyPath">The current property path.</param>
        /// <returns>The list of validation errors.</returns>
        protected virtual ICollection<ValidationError> Validate(JToken token, JsonSchema4 schema, string propertyName,
            string propertyPath)
        {
            List<ValidationError> errors = new List<ValidationError>();

            ValidateAnyOf(token, schema, propertyName, propertyPath, errors);
            ValidateAllOf(token, schema, propertyName, propertyPath, errors);
            ValidateOneOf(token, schema, propertyName, propertyPath, errors);
            ValidateNot(token, schema, propertyName, propertyPath, errors);
            ValidateType(token, schema, propertyName, propertyPath, errors);
            ValidateEnum(token, schema, propertyName, propertyPath, errors);
            ValidateProperties(token, schema, propertyName, propertyPath, errors);

            return errors;
        }

        private void ValidateAdditionalItems(JToken item, JsonSchema4 schema, int index, string propertyPath,
            List<ValidationError> errors)
        {
            if (schema.Items.Count > 0)
            {
                string propertyIndex = string.Format("[{0}]", index);
                if (schema.Items.Count > index)
                {
                    ChildSchemaValidationError error = TryCreateChildSchemaError(item,
                        schema.Items.ElementAt(index), ValidationErrorKind.ArrayItemNotValid, propertyIndex,
                        propertyPath + propertyIndex);
                    if (error != null)
                    {
                        errors.Add(error);
                    }
                }
                else if (schema.AdditionalItemsSchema != null)
                {
                    ChildSchemaValidationError error = TryCreateChildSchemaError(item,
                        schema.AdditionalItemsSchema, ValidationErrorKind.AdditionalItemNotValid, propertyIndex,
                        propertyPath + propertyIndex);
                    if (error != null)
                    {
                        errors.Add(error);
                    }
                }
                else if (!schema.AllowAdditionalItems)
                {
                    errors.Add(new ValidationError(ValidationErrorKind.TooManyItemsInTuple,
                        propertyIndex, propertyPath + propertyIndex, item, schema));
                }
            }
        }

        private void ValidateAdditionalProperties(JToken token, List<JProperty> additionalProperties,
            JsonSchema4 schema,
            string propertyName, string propertyPath, List<ValidationError> errors)
        {
            if (schema.AdditionalPropertiesSchema != null)
            {
                foreach (JProperty property in additionalProperties)
                {
                    ChildSchemaValidationError error = TryCreateChildSchemaError(property.Value,
                        schema.AdditionalPropertiesSchema, ValidationErrorKind.AdditionalPropertiesNotValid,
                        property.Name, property.Path);
                    if (error != null)
                    {
                        errors.Add(error);
                    }
                }
            }
            else if (!schema.AllowAdditionalProperties && additionalProperties.Any())
            {
                foreach (JProperty property in additionalProperties)
                {
                    string newPropertyPath = !string.IsNullOrEmpty(propertyPath)
                        ? propertyPath + "." + property.Name
                        : property.Name;
                    errors.Add(new ValidationError(ValidationErrorKind.NoAdditionalPropertiesAllowed, property.Name,
                        newPropertyPath, property, schema));
                }
            }
        }

        private void ValidateAllOf(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            if (schema.AllOf.Count > 0)
            {
                Dictionary<JsonSchema4, ICollection<ValidationError>> propertyErrors =
                    schema.AllOf.ToDictionary(s => s, s => Validate(token, s));
                if (propertyErrors.Any(s => s.Value.Count != 0))
                {
                    errors.Add(new ChildSchemaValidationError(ValidationErrorKind.NotAllOf, propertyName, propertyPath,
                        propertyErrors, token, schema));
                }
            }
        }

        private void ValidateAnyOf(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            if (schema.AnyOf.Count > 0)
            {
                Dictionary<JsonSchema4, ICollection<ValidationError>> propertyErrors =
                    schema.AnyOf.ToDictionary(s => s, s => Validate(token, s));
                if (propertyErrors.All(s => s.Value.Count != 0))
                {
                    errors.Add(new ChildSchemaValidationError(ValidationErrorKind.NotAnyOf, propertyName, propertyPath,
                        propertyErrors, token, schema));
                }
            }
        }

        private void ValidateArray(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (token is JArray array)
            {
                if (schema.MinItems > 0 && array.Count < schema.MinItems)
                {
                    errors.Add(new ValidationError(ValidationErrorKind.TooFewItems, propertyName, propertyPath, token,
                        schema));
                }

                if (schema.MaxItems > 0 && array.Count > schema.MaxItems)
                {
                    errors.Add(new ValidationError(ValidationErrorKind.TooManyItems, propertyName, propertyPath, token,
                        schema));
                }

                if (schema.UniqueItems && array.Count != array.Select(a => a.ToString()).Distinct().Count())
                {
                    errors.Add(new ValidationError(ValidationErrorKind.ItemsNotUnique, propertyName, propertyPath,
                        token, schema));
                }

                for (int index = 0; index < array.Count; index++)
                {
                    JToken item = array[index];

                    string propertyIndex = string.Format("[{0}]", index);
                    string itemPath = !string.IsNullOrEmpty(propertyPath)
                        ? propertyPath + propertyIndex
                        : propertyIndex;

                    if (schema.Item != null)
                    {
                        ChildSchemaValidationError error = TryCreateChildSchemaError(item, schema.Item,
                            ValidationErrorKind.ArrayItemNotValid, propertyIndex, itemPath);
                        if (error != null)
                        {
                            errors.Add(error);
                        }
                    }

                    ValidateAdditionalItems(item, schema, index, propertyPath, errors);
                }
            }
            else if (type.HasFlag(JsonObjectType.Array))
            {
                errors.Add(new ValidationError(ValidationErrorKind.ArrayExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateBoolean(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (type.HasFlag(JsonObjectType.Boolean) && token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.BooleanExpected, propertyName, propertyPath, token,
                        schema));
                }
                return;
            }
            
            if (type.HasFlag(JsonObjectType.Boolean) && token.Type != JTokenType.Boolean)
            {
                errors.Add(new ValidationError(ValidationErrorKind.BooleanExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateEnum(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            if (schema.Enumeration.Contains(null) && token?.Type == JTokenType.Null)
            {
                return;
            }

            if (schema.Enumeration.Count > 0 && schema.Enumeration.All(v => v?.ToString() != token?.ToString()))
            {
                errors.Add(new ValidationError(ValidationErrorKind.NotInEnumeration, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateInteger(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (type.HasFlag(JsonObjectType.Integer) && token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.IntegerExpected, propertyName, propertyPath, token,
                        schema));
                }
                return;
            }
            
            if (type.HasFlag(JsonObjectType.Integer) && token.Type != JTokenType.Integer)
            {
                errors.Add(new ValidationError(ValidationErrorKind.IntegerExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateMaxProperties(JToken token, IList<JProperty> properties, JsonSchema4 schema,
            string propertyName, string propertyPath, List<ValidationError> errors)
        {
            if (schema.MaxProperties > 0 && properties.Count() > schema.MaxProperties)
            {
                errors.Add(new ValidationError(ValidationErrorKind.TooManyProperties, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateMinProperties(JToken token, IList<JProperty> properties, JsonSchema4 schema,
            string propertyName, string propertyPath, List<ValidationError> errors)
        {
            if (schema.MinProperties > 0 && properties.Count() < schema.MinProperties)
            {
                errors.Add(new ValidationError(ValidationErrorKind.TooFewProperties, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateNot(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            if (schema.Not != null && Validate(token, schema.Not).Count == 0)
            {
                errors.Add(new ValidationError(ValidationErrorKind.ExcludedSchemaValidates, propertyName, propertyPath,
                    token, schema));
            }
        }

        private void ValidateNull(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (type.HasFlag(JsonObjectType.Null) && token != null && token.Type != JTokenType.Null)
            {
                errors.Add(new ValidationError(ValidationErrorKind.NullExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateNumber(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (type.HasFlag(JsonObjectType.Number) && token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.NumberExpected, propertyName, propertyPath, token,
                        schema));
                }
                return;
            }
            
            if (type.HasFlag(JsonObjectType.Number) && token.Type != JTokenType.Float &&
                token.Type != JTokenType.Integer)
            {
                errors.Add(new ValidationError(ValidationErrorKind.NumberExpected, propertyName, propertyPath, token,
                    schema));
            }

            if (token.Type == JTokenType.Float || token.Type == JTokenType.Integer)
            {
                try
                {
                    decimal value = token.Value<decimal>();

                    if (schema.Minimum.HasValue &&
                        (schema.IsExclusiveMinimum ? value <= schema.Minimum : value < schema.Minimum))
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooSmall, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.Maximum.HasValue &&
                        (schema.IsExclusiveMaximum ? value >= schema.Maximum : value > schema.Maximum))
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooBig, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.ExclusiveMinimum.HasValue && value <= schema.ExclusiveMinimum)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooSmall, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.ExclusiveMaximum.HasValue && value >= schema.ExclusiveMaximum)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooBig, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.MultipleOf.HasValue && value % schema.MultipleOf != 0)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberNotMultipleOf, propertyName,
                            propertyPath, token, schema));
                    }
                }
                catch (OverflowException)
                {
                    double value = token.Value<double>();

                    if (schema.Minimum.HasValue && (schema.IsExclusiveMinimum
                            ? value <= (double) schema.Minimum
                            : value < (double) schema.Minimum))
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooSmall, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.Maximum.HasValue && (schema.IsExclusiveMaximum
                            ? value >= (double) schema.Maximum
                            : value > (double) schema.Maximum))
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooBig, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.ExclusiveMinimum.HasValue && value <= (double) schema.ExclusiveMinimum)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooSmall, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.ExclusiveMaximum.HasValue && value >= (double) schema.ExclusiveMaximum)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberTooBig, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.MultipleOf.HasValue && value % (double) schema.MultipleOf != 0)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.NumberNotMultipleOf, propertyName,
                            propertyPath, token, schema));
                    }
                }
            }
        }

        private void ValidateObject(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            if (type.HasFlag(JsonObjectType.Object) && token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.ObjectExpected, propertyName, propertyPath, token,
                        schema));
                }
                return;
            }
            
            if (type.HasFlag(JsonObjectType.Object) && !(token is JObject))
            {
                errors.Add(new ValidationError(ValidationErrorKind.ObjectExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateOneOf(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            if (token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.ObjectExpected, propertyName, propertyPath, token,
                        schema));
                }
            }
            else if (schema.OneOf.Count > 0)
            {
                Dictionary<JsonSchema4, ICollection<ValidationError>> propertyErrors =
                    schema.OneOf.ToDictionary(s => s, s => Validate(token, s));
                if (propertyErrors.Count(s => s.Value.Count == 0) != 1)
                {
                    errors.Add(new ChildSchemaValidationError(ValidationErrorKind.NotOneOf, propertyName, propertyPath,
                        propertyErrors, token, schema));
                }
            }
        }

        private void ValidatePatternProperties(List<JProperty> additionalProperties, JsonSchema4 schema,
            List<ValidationError> errors)
        {
            foreach (JProperty property in additionalProperties.ToArray())
            {
                KeyValuePair<string, JsonProperty> patternPropertySchema =
                    schema.PatternProperties.FirstOrDefault(p => Regex.IsMatch(property.Name, p.Key));
                if (patternPropertySchema.Value != null)
                {
                    ChildSchemaValidationError error = TryCreateChildSchemaError(property.Value,
                        patternPropertySchema.Value, ValidationErrorKind.AdditionalPropertiesNotValid, property.Name,
                        property.Path);

                    if (error != null)
                    {
                        errors.Add(error);
                    }

                    additionalProperties.Remove(property);
                }
            }
        }

        private void ValidateProperties(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            JObject obj = token as JObject;
            if (obj == null && schema.Type.HasFlag(JsonObjectType.Null))
            {
                return;
            }

            foreach (KeyValuePair<string, JsonProperty> propertyInfo in schema.Properties)
            {
                string newPropertyPath = GetPropertyPath(propertyPath, propertyInfo.Key);

                JProperty property = obj?.Property(propertyInfo.Key);
                if (property != null)
                {
                    ICollection<ValidationError> propertyErrors = Validate(property.Value,
                        propertyInfo.Value.ActualSchema, propertyInfo.Key, newPropertyPath);
                    errors.AddRange(propertyErrors);
                }
                else if (propertyInfo.Value.IsRequired)
                {
                    errors.Add(new ValidationError(ValidationErrorKind.PropertyRequired, propertyInfo.Key,
                        newPropertyPath, token, schema));
                }
            }

            // Properties may be required in a schema without being specified as a property.
            foreach (string requiredProperty in schema.RequiredProperties)
            {
                if (schema.Properties.ContainsKey(requiredProperty))
                {
                    // The property has already been checked.
                    continue;
                }

                string newPropertyPath = GetPropertyPath(propertyPath, requiredProperty);
                if (obj?.Property(requiredProperty) == null)
                {
                    errors.Add(new ValidationError(ValidationErrorKind.PropertyRequired, requiredProperty,
                        newPropertyPath, token, schema));
                }
            }

            if (obj != null)
            {
                List<JProperty> properties = obj.Properties().ToList();

                ValidateMaxProperties(token, properties, schema, propertyName, propertyPath, errors);
                ValidateMinProperties(token, properties, schema, propertyName, propertyPath, errors);

                List<JProperty> additionalProperties =
                    properties.Where(p => !schema.Properties.ContainsKey(p.Name)).ToList();

                ValidatePatternProperties(additionalProperties, schema, errors);
                ValidateAdditionalProperties(token, additionalProperties, schema, propertyName, propertyPath, errors);
            }
        }

        private void ValidateString(JToken token, JsonSchema4 schema, JsonObjectType type, string propertyName,
            string propertyPath, List<ValidationError> errors)
        {
            bool isString = token.Type == JTokenType.String || token.Type == JTokenType.Date ||
                            token.Type == JTokenType.Guid || token.Type == JTokenType.TimeSpan ||
                            token.Type == JTokenType.Uri;

            if (isString)
            {
                string value = token.Type == JTokenType.Date
                    ? (token as JValue).ToString("yyyy-MM-ddTHH:mm:ssK")
                    : token.Value<string>();
                if (value != null)
                {
                    if (!string.IsNullOrEmpty(schema.Pattern))
                    {
                        if (!Regex.IsMatch(value, schema.Pattern))
                        {
                            errors.Add(new ValidationError(ValidationErrorKind.PatternMismatch, propertyName,
                                propertyPath, token, schema));
                        }
                    }

                    if (schema.MinLength.HasValue && value.Length < schema.MinLength)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.StringTooShort, propertyName, propertyPath,
                            token, schema));
                    }

                    if (schema.MaxLength.HasValue && value.Length > schema.MaxLength)
                    {
                        errors.Add(new ValidationError(ValidationErrorKind.StringTooLong, propertyName, propertyPath,
                            token, schema));
                    }

                    if (!string.IsNullOrEmpty(schema.Format)
                        && _formatValidatorsMap.TryGetValue(schema.Format, out IFormatValidator formatValidator)
                        && !formatValidator.IsValid(value, token.Type))
                    {
                        ValidationError error = new ValidationError(
                            formatValidator.ValidationErrorKind,
                            propertyName,
                            propertyPath,
                            token,
                            schema);

                        errors.Add(error);
                    }
                }
            }
            else if (type.HasFlag(JsonObjectType.String) && token.Type == JTokenType.Null)
            {
                if (!schema.IsNullable(_schemaType))
                {
                    errors.Add(new ValidationError(ValidationErrorKind.StringExpected, propertyName, propertyPath, token,
                        schema));
                }
            }
            else if (type.HasFlag(JsonObjectType.String))
            {
                errors.Add(new ValidationError(ValidationErrorKind.StringExpected, propertyName, propertyPath, token,
                    schema));
            }
        }

        private void ValidateType(JToken token, JsonSchema4 schema, string propertyName, string propertyPath,
            List<ValidationError> errors)
        {
            Dictionary<JsonObjectType, ICollection<ValidationError>> types = GetTypes(schema)
                .ToDictionary(t => t, t => (ICollection<ValidationError>) new List<ValidationError>());
            if (types.Count > 1)
            {
                foreach (KeyValuePair<JsonObjectType, ICollection<ValidationError>> type in types)
                {
                    ValidateArray(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateString(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateNumber(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateInteger(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateBoolean(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateNull(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                    ValidateObject(token, schema, type.Key, propertyName, propertyPath,
                        (List<ValidationError>) type.Value);
                }

                // just one has to validate when multiple types are defined
                if (types.All(t => t.Value.Count > 0))
                {
                    errors.Add(new MultiTypeValidationError(
                        ValidationErrorKind.NoTypeValidates, propertyName, propertyPath, types, token, schema));
                }
            }
            else
            {
                ValidateArray(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateString(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateNumber(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateInteger(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateBoolean(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateNull(token, schema, schema.Type, propertyName, propertyPath, errors);
                ValidateObject(token, schema, schema.Type, propertyName, propertyPath, errors);
            }
        }

        #endregion
    }
```
Thanks you for your time on this project and this PR.

**Comment by RicoSuter** [comment]
Ok, but why shouldnt we just use your version?

**Comment by gcelet** [comment]
Hi,

Honestly, i use my version only with open api 3.0 and only for one way of defining a schema with nullable type. 

I'm really not sure that this version is really robust for other use case that my own: that's the reason i would like to add some unit tests around this feature. But i tried to add some testing around that but i couldn't see a way to define a open api 3.0 schema with nullable type for a unit test.

But this version can be a starting point for a real robust version.

**Comment by SebastianStehle** [comment]
@RicoSuter I have a problem with this as well. Are you planning to fix it yourself?

**Comment by SebastianStehle** [comment]
I made a new PR: https://github.com/RicoSuter/NJsonSchema/pull/1394

**Comment by RicoSuter** [comment]
Closed in favor of #1394

**Pull request closed without merging**
