### PR TITLE
remove JsonInheritanceAttribute in abstract class

### PR DESCRIPTION
**Pull request by Goxiaoy**
abstract class can not be instantiate

### CODE REVIEW

**Comment by RicoSuter** [comment]
Are you sure we can just remove it? I think this is needed so that the deserializer knows the possible implementations of the (abstract) base class.

**Comment by Goxiaoy** [comment]
I think so.
Look at the function `ReadJson` in generated class `JsonInheritanceConverter`

```
var discriminator = Newtonsoft.Json.Linq.Extensions.Value<string>(jObject.GetValue(_discriminator));
var subtype = GetObjectSubtype(objectType, discriminator);

var objectContract = serializer.ContractResolver.ResolveContract(subtype) as Newtonsoft.Json.Serialization.JsonObjectContract;
if (objectContract == null || System.Linq.Enumerable.All(objectContract.Properties, p => p.PropertyName != _discriminator))
{
    jObject.Remove(_discriminator);
}

try
{
    _isReading = true;
    return serializer.Deserialize(jObject.CreateReader(), subtype);
}
finally
{
    _isReading = false;
}
```
When subtype is an abstract type, `serializer.Deserialize(jObject.CreateReader(), subtype);` will raise an error because abstract class can not be instantiate.

**Comment by RicoSuter** [comment]
Ok yes, makes sense.

**Comment by RicoSuter** [comment]
Thanks for the PR.

**Pull request merged**
