### PR TITLE
Support oneOf inheritance for JsonSchema Generation #832

### PR DESCRIPTION
**Pull request by alb3ric**
Hello,

Just made some modifications to generate a jsonschema with oneOf inheritance. I didn't do anything for CodeGeneration as don't need it. 
For schema generation do you think it is the way to go? And what did you think about when you mention inheritanceMode ? (which kind of mode would you propose?)

### CODE REVIEW

**Comment by RSuter** [comment]
Refs: 

- #832
- #13
- #302

**Comment by paul-michalik** [comment]
Any progress on this?

**Comment by qub1n** [comment]
> Any progress on this?

This one is about generating C# OneOf from JsonSchema OneOf.
Is any progress in another direction? I mean generating JsonSchema OneOf from C#  OneOf?

**Comment by darkflame0** [comment]
> > Any progress on this?
> 
> This one is about generating C# OneOf from JsonSchema OneOf. Is any progress in another direction? I mean generating JsonSchema OneOf from C# OneOf?

@RicoSuter Is any progress for it?
I really need it...

**Comment by icnocop** [comment]
Hi.

As a work-around I was able to use an operation processor.

See https://gist.github.com/icnocop/10de946939e5046190219cc8817356c4

It works for my case, but may not be the best solution, and may not support all scenarios.

For example, it may have been better to use a schema processor instead.

Usage, in Startup.cs, in ConfigureServices:
```
services.AddOpenApiDocument((settings, serviceProvider) =>
{
    settings.FlattenInheritanceHierarchy = true;
    settings.SchemaType = SchemaType.OpenApi3;
    settings.OperationProcessors.Add(new OneOfOperationProcessor());
    settings.AllowReferencesWithProperties = true;
});
```

My types are defined and decorated similar to the following:
```
[KnownType(typeof(ItemA))]
[KnownType(typeof(ItemB))]
[JsonConverter(typeof(JsonInheritanceConverter), "discriminator")]
[JsonInheritance("A", typeof(ItemA))]
[JsonInheritance("B", typeof(ItemB))]
public abstract class Item
{
}

public class ItemA : Item
{
}

public class ItemB : Item
{
}
```

I only tested with types, and generic types with one generic type parameter.

**Comment by RicoSuter** [comment]
Very old PR, closing now. Please open another PR against recent source if this is still an issue.

**Pull request closed without merging**
