### PR TITLE
Fix ConvertCSharpDocs multi-line regression

### LINKED ISSUE #1462: Multiline comments generation issue
Hello, after PR #1346 code generation for multiline comments produces invalid `<summary>` xml doc.

For example:

```yaml
    TestType:
      type: object
      properties:
        code:
          type: string
          description: |
            * test1
            * test2
```

produces the following c# code:

```csharp
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.15.3.0 (NJsonSchema v10.6.4.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TestType
    {
        /// <summary>* test1
        /// <br/>* test2
    </summary>
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }
```

As you see the closing `</summary>` tag doesn't start with `///` which breaks the compilation

### PR DESCRIPTION
**Pull request by lahma**
Reverted back to old logic, added unit test, changed summary format to span multiple lines so multi-line ones don't look weird.

fixes #1462
fixes [#3793](https://github.com/RicoSuter/NSwag/issues/3793)

### CODE REVIEW

**Comment by RicoSuter** [comment]
It's a dangerous fix as it requires a template change (some might have custom templates).

**Comment by lahma** [comment]
Old templates should work as-is. Now the built-in ones just add new line before and after the actual content:

```csharp
/// <summary>OLD_INSERTED_DATA</summary>
```

```csharp
/// <summary>
/// OLD_INSERTED_DATA
/// </summary>
```
The c# part is the sample, it just appends the same data to different valid doc comment section.

**Comment by RicoSuter** [comment]
Need to fix those in NSwag as well, right?

image

**Comment by lahma** [comment]
These should work without changes, but syncing the logic of having separate line might make sense.

**Pull request merged**
