### PR TITLE
Expose the ExtensionData's keys as a separate collection

### PR DESCRIPTION
**Pull request by michsco**
The current `ExtensionData` dictionary only allows values to be accessed if the key is known ahead of time. Unfortunately, due to how DotLiquid handles dictionaries, there isn't a way to loop through the keys. This PR will expose the extension data keys for use in templates.

### CODE REVIEW

**Comment by michsco** [comment]
@RicoSuter -- you may have more experience with the `Drop` and `IIndexable` interfaces, but creating a new collection was the only way I could figure out to maintain backward compatibility.

**Comment by RicoSuter** [comment]
> you may have more experience with the Drop and IIndexable interfaces, but creating a new collection was the only way I could figure out to maintain backward compatibility

You mean this is the only way to actually iterate the keys in a template?

**Comment by michsco** [comment]
> You mean this is the only way to actually iterate the keys in a template?

Correct.

**Comment by michsco** [comment]
Once you approve this PR, how long does it take to flow back to the NuGet packages?

**Comment by RicoSuter** [comment]
Why did you close/delete the PR?

**Comment by michsco** [comment]
I realized the enumeration wasn't needed for my scenario as I can just as easily collapse my annotations into a single known extension if I am able to get the annotations PR template in.

**Pull request closed without merging**
